#!/bin/bash
# import a mysql dump file to a database
# gunzip dump file if dump file name is *.gz

# vars
NAME=$(basename $0)
USAGE=$(printf "Usage: %s: [-h] DB_NAME SQL_DUMP_FILE" $NAME)

# commands
CMD_MYSQL="mysql --defaults-file=/etc/mysql/debian.cnf"

# parse optionals args
while getopts 'h' OPTION
do
    case $OPTION in
    h)
        printf "$USAGE\n"
        printf "import a database from an SQL dump file (gunzipped for *.gz name)\n"
        printf "  -h    print this help message\n"
        exit 0
        ;;
    esac
done
shift $(($OPTIND - 1))

# parse fixed args
DB=$1
DUMP=$2

# some checks
[ $EUID -ne 0 ] && { printf "ERROR: $NAME needs to be run by root\n" 1>&2; exit 1; }
[ $# -ne 2 ] && { printf "$USAGE\n" 1>&2; exit 1; }
[ ! -f $DUMP ] && { printf "ERROR: %s is not a regular file\n" $DUMP 1>&2; exit 1; }

# import with zcat if *.gz
if [[ $DUMP =~ \.gz$ ]]
then
    zcat $DUMP | $CMD_MYSQL $DB
else
    cat $DUMP | $CMD_MYSQL $DB
fi
